Sprint 1/step 2
artem-benda/react-burger pull request #2
Opened 2022-05-26 15:24 UTC by artem-benda

2022-05-26 16:08 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

> Добавьте проверку ответа сервера - res.ok:
> 
> Например:
> 
> ```
> .then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
> ```
> 
> иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение
> 
> [https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)
> 
> [https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)
> 
> Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию
> 
> ```
> const checkReponse = (res) => {
>   return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
> };
> ```
> 
> `fetch(someUrl).then(checkReponse)`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-05-26 16:08 UTC, andryxxa93 commented on src/utils/data.js
> +}
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-05-26 16:08 UTC, andryxxa93 commented on src/utils/data.js
> +const API_BASE_URL = "https://norma.nomoreparties.space/api";
**Отлично**
Вы вынесли запрос в отдельный и очень грамотно его оформили

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/app/app.jsx
> +                selectedIngredients={ingredients.filter(ingredient => ingredient.type === 'main' || ingredient.type === 'sauce')}
**Можно лучше**
Такие операции лучше выносить из верстки в функции, так удобнее будет читать код править его

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +        ( (props.bunIngredient && props.bunIngredient.price) || 0) * 2;
**Можно лучше**
Такие операции лучше оборачивать в useMemo, это поможет избежать лишний перерасчетов стоимости

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                }
**Можно лучше**
Нет смысла делать условный рендеринг тут. Вряд ли какая-то категория будет отсутствовать.

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    )
**Можно лучше**
Логику (функцию фильтрации) лучше выносить из верстки. К тому же тут налицо повторение одной той же логики 3 раза. Можно сделать универсальную функцию, куда достаточно будет передать название категории, а она вернёт нужный список ингредиентов.

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +                </div>
**Можно улучшить**
Тут есть повторение верстки, её желательно вынести в отдельный компонент и переиспользовать

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.jsx
> +}
**Можно улучшить**

У ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +    }, [onDismiss])
**Можно лучше**
Тут достаточно просто оставить пустой массив, тогда useEffect сработает только при 1 раз при монтировании компонента. Функция onDismiss имеет ссылочный тип (https://doka.guide/js/ref-type-vs-value-type) и поэтому react будет сравнивать её не по значению, а по ссылка. Ссылка каждый раз будет новой, что будет вызывать лишний раз useEffect.
<img width="1432" alt="Снимок экрана 2022-05-26 в 18 55 12" src="https://user-images.githubusercontent.com/60173362/170526231-372d548f-7121-4dff-87ed-42b7a1d2735e.png">

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +            document.removeEventListener('keydown', escKeyboardHandler);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +            <ModalOverlay onClick={onOverlayClick}>
**Можно улучшить**
 ModalOverlay просто компонент подложки а не контейнер

2022-05-26 16:08 UTC, andryxxa93 commented on src/components/app/app.module.css
> +    height: 0px;
**Можно улучшить**
Когда используется нулевое значение, то единицы измерения (px) ставить не нужно

2022-05-27 05:37 UTC, artem-benda commented on src/components/modal/modal.jsx
> +    }, [onDismiss])
Пожалуй, оставлю как есть. В предложенном варианте при сборке получаю Warning:

WARNING in src\components\modal\modal.jsx
  Line 23:8:  React Hook useEffect has a missing dependency: 'onDismiss'. Either include it or remove the dependency array. If 'onDismiss' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

Очень не хотелось бы засорять проект warning'ами. Знаем к чему такое приводит, будут сотни таких Warning'ов, на которые уже никто не будет обращать внимание.

В качестве оптимизации думаю, можно обернуть ф-цию в useCallback в использующем Modal компоненте. Но пока оставляю как есть, считаю что оптимизация не сильно нужна здесь.

2022-05-27 05:40 UTC, artem-benda commented on src/utils/data.js
> +}
исправлено

2022-05-27 05:40 UTC, artem-benda commented on src/components/burger-constructor/burger-constructor.jsx
> +        ( (props.bunIngredient && props.bunIngredient.price) || 0) * 2;
исправлено

2022-05-27 05:40 UTC, artem-benda commented on src/components/modal-overlay/modal-overlay.jsx
> +}
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/modal/modal.jsx
> +            <ModalOverlay onClick={onOverlayClick}>
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/app/app.module.css
> +    height: 0px;
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/burger-constructor/burger-constructor.jsx
> +function BurgerConstructor(props) {
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/app/app.jsx
> +                selectedIngredients={ingredients.filter(ingredient => ingredient.type === 'main' || ingredient.type === 'sauce')}
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                }
исправлено

2022-05-27 05:41 UTC, artem-benda commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    )
исправлено

2022-05-27 05:42 UTC, artem-benda commented on src/components/ingredient-details/ingredient-details.jsx
> +                </div>
исправлено

2022-05-27 18:51 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2022-05-27 18:51 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +            if (event.key === 'Escape') {
**Здорово** 
Вы реализовали закрытие модальных окон помощью клика на оверлей и ESC!

2022-05-28 02:41 UTC, merged